const countryTrans = {
  AD: {
    country: "AD",
    iso_3166_1: "AND",
    name_tw: "安道爾公國",
    name_en: "Andorra",
  },
  AE: {
    country: "AE",
    iso_3166_1: "ARE",
    name_tw: "阿拉伯聯合大公國",
    name_en: "United Arab Emirates",
  },
  AF: {
    country: "AF",
    iso_3166_1: "AFG",
    name_tw: "阿富汗 ",
    name_en: "Afghanistan",
  },
  AG: {
    country: "AG",
    iso_3166_1: "ATG",
    name_tw: "安提瓜及巴布達 ",
    name_en: "Antigua and Barbuda",
  },
  AI: {
    country: "AI",
    iso_3166_1: "AIA",
    name_tw: "安圭拉 ",
    name_en: "Anguilla",
  },
  AL: {
    country: "AL",
    iso_3166_1: "ALB",
    name_tw: "阿爾巴尼亞 ",
    name_en: "Albania",
  },
  AM: {
    country: "AM",
    iso_3166_1: "ARM",
    name_tw: "亞美尼亞 ",
    name_en: "Armenia",
  },
  AN: {
    country: "AN",
    iso_3166_1: "ANT",
    name_tw: "荷屬安的列斯 ",
    name_en: "Netherlands Antilles",
  },
  ANO: {
    country: "ANO",
    iso_3166_1: "ANO",
    name_tw: "澳洲與大洋洲 ",
    name_en: "Australia & Oceania",
  },
  AO: {
    country: "AO",
    iso_3166_1: "AGO",
    name_tw: "安哥拉 ",
    name_en: "Angola",
  },
  AQ: {
    country: "AQ",
    iso_3166_1: "ATA",
    name_tw: "南極 ",
    name_en: "Antarctica",
  },
  AR: {
    country: "AR",
    iso_3166_1: "ARG",
    name_tw: "阿根廷 ",
    name_en: "Argentina",
  },
  AS: {
    country: "AS",
    iso_3166_1: "ASM",
    name_tw: "美屬薩摩亞 ",
    name_en: "American Samoa",
  },
  ASIA: {
    country: "ASIA",
    iso_3166_1: "ASI",
    name_tw: "亞洲 ",
    name_en: "Asia",
  },
  AT: {
    country: "AT",
    iso_3166_1: "AUT",
    name_tw: "奧地利 ",
    name_en: "Austria",
  },
  AU: {
    country: "AU",
    iso_3166_1: "AUS",
    name_tw: "澳大利亞 ",
    name_en: "Australia",
  },
  AW: {
    country: "AW",
    iso_3166_1: "ABW",
    name_tw: "阿魯巴 ",
    name_en: "Aruba",
  },
  AZ: {
    country: "AZ",
    iso_3166_1: "AZE",
    name_tw: "亞塞拜疆 ",
    name_en: "Azerbaijan",
  },
  BA: {
    country: "BA",
    iso_3166_1: "BIH",
    name_tw: "波士尼亞與赫塞哥維納",
    name_en: "Bosnia and Herzegovina",
  },
  BB: {
    country: "BB",
    iso_3166_1: "BRB",
    name_tw: "巴巴多斯 ",
    name_en: "Barbados",
  },
  BD: {
    country: "BD",
    iso_3166_1: "BGD",
    name_tw: "孟加拉國 ",
    name_en: "Bangladesh",
  },
  BE: {
    country: "BE",
    iso_3166_1: "BEL",
    name_tw: "比利時 ",
    name_en: "Belgium",
  },
  BF: {
    country: "BF",
    iso_3166_1: "BFA",
    name_tw: "布吉納法索",
    name_en: "Burkina Faso",
  },
  BG: {
    country: "BG",
    iso_3166_1: "BGR",
    name_tw: "保加利亞 ",
    name_en: "Bulgaria",
  },
  BH: {
    country: "BH",
    iso_3166_1: "BHR",
    name_tw: "巴林 ",
    name_en: "Bahrain",
  },
  BI: {
    country: "BI",
    iso_3166_1: "BDI",
    name_tw: "布隆迪 ",
    name_en: "Burundi",
  },
  BJ: {
    country: "BJ",
    iso_3166_1: "BEN",
    name_tw: "貝寧 ",
    name_en: "Benin",
  },
  BL: {
    country: "BL",
    iso_3166_1: "BLM",
    name_tw: "聖巴泰勒米島 ",
    name_en: "Saint Barthelemy",
  },
  BM: {
    country: "BM",
    iso_3166_1: "BMU",
    name_tw: "百慕達",
    name_en: "Bermuda",
  },
  BN: {
    country: "BN",
    iso_3166_1: "BRN",
    name_tw: "汶萊",
    name_en: "Brunei",
  },
  BO: {
    country: "BO",
    iso_3166_1: "BOL",
    name_tw: "玻利維亞 ",
    name_en: "Bolivia",
  },
  BR: {
    country: "BR",
    iso_3166_1: "BRA",
    name_tw: "巴西 ",
    name_en: "Brazil",
  },
  BS: {
    country: "BS",
    iso_3166_1: "BHS",
    name_tw: "巴哈馬 ",
    name_en: "Bahamas",
  },
  BT: {
    country: "BT",
    iso_3166_1: "BTN",
    name_tw: "不丹 ",
    name_en: "Bhutan",
  },
  BW: {
    country: "BW",
    iso_3166_1: "BWA",
    name_tw: "波札那",
    name_en: "Botswana",
  },
  BY: {
    country: "BY",
    iso_3166_1: "BLR",
    name_tw: "白俄羅斯 ",
    name_en: "Belarus",
  },
  BZ: {
    country: "BZ",
    iso_3166_1: "BLZ",
    name_tw: "貝里斯",
    name_en: "Belize",
  },
  CA: {
    country: "CA",
    iso_3166_1: "CAN",
    name_tw: "加拿大 ",
    name_en: "Canada",
  },
  CC: {
    country: "CC",
    iso_3166_1: "CCK",
    name_tw: "科科斯群島 ",
    name_en: "Cocos (Keeling) Islands",
  },
  CD: {
    country: "CD",
    iso_3166_1: "COD",
    name_tw: "剛果民主共和國 ",
    name_en: "Democratic Republic of the Congo",
  },
  CF: {
    country: "CF",
    iso_3166_1: "CAF",
    name_tw: "中非共和國 ",
    name_en: "Central African Republic",
  },
  CG: {
    country: "CG",
    iso_3166_1: "COG",
    name_tw: "剛果共和國 ",
    name_en: "Republic of the Congo",
  },
  CH: {
    country: "CH",
    iso_3166_1: "CHE",
    name_tw: "瑞士 ",
    name_en: "Switzerland",
  },
  CI: {
    country: "CI",
    iso_3166_1: "CIV",
    name_tw: "象牙海岸 ",
    name_en: "Ivory Coast",
  },
  CK: {
    country: "CK",
    iso_3166_1: "COK",
    name_tw: "庫克群島 ",
    name_en: "Cook Islands",
  },
  CL: {
    country: "CL",
    iso_3166_1: "CHL",
    name_tw: "智利 ",
    name_en: "Chile",
  },
  CM: {
    country: "CM",
    iso_3166_1: "CMR",
    name_tw: "喀麥隆 ",
    name_en: "Cameroon",
  },
  CN: {
    country: "CN",
    iso_3166_1: "CHN",
    name_tw: "中國 ",
    name_en: "China",
  },
  CO: {
    country: "CO",
    iso_3166_1: "COL",
    name_tw: "哥倫比亞 ",
    name_en: "Colombia",
  },
  CR: {
    country: "CR",
    iso_3166_1: "CRC",
    name_tw: "哥斯達黎加 ",
    name_en: "Costa Rica",
  },
  CU: { country: "CU", iso_3166_1: "CUB", name_tw: "古巴 ", name_en: "Cuba" },
  CV: {
    country: "CV",
    iso_3166_1: "CPV",
    name_tw: "維德角",
    name_en: "Cape Verde",
  },
  CX: {
    country: "CX",
    iso_3166_1: "CXR",
    name_tw: "聖誕島 ",
    name_en: "Christmas Island",
  },
  CY: {
    country: "CY",
    iso_3166_1: "CYP",
    name_tw: "賽普勒斯",
    name_en: "Cyprus",
  },
  CZ: {
    country: "CZ",
    iso_3166_1: "CZE",
    name_tw: "捷克共和國 ",
    name_en: "Czech Republic",
  },
  DE: {
    country: "DE",
    iso_3166_1: "DEU",
    name_tw: "德國 ",
    name_en: "Germany",
  },
  DJ: {
    country: "DJ",
    iso_3166_1: "DJI",
    name_tw: "吉布地",
    name_en: "Djibouti",
  },
  DK: {
    country: "DK",
    iso_3166_1: "DNK",
    name_tw: "丹麥 ",
    name_en: "Denmark",
  },
  DM: {
    country: "DM",
    iso_3166_1: "DMA",
    name_tw: "多米尼克",
    name_en: "Dominica",
  },
  DO: {
    country: "DO",
    iso_3166_1: "DOM",
    name_tw: "多明尼加共和國 ",
    name_en: "Dominican Republic",
  },
  DZ: {
    country: "DZ",
    iso_3166_1: "DZA",
    name_tw: "阿爾及利亞 ",
    name_en: "Algeria",
  },
  EC: {
    country: "EC",
    iso_3166_1: "ECU",
    name_tw: "厄瓜多",
    name_en: "Ecuador",
  },
  EE: {
    country: "EE",
    iso_3166_1: "EST",
    name_tw: "愛沙尼亞 ",
    name_en: "Estonia",
  },
  EG: {
    country: "EG",
    iso_3166_1: "EGY",
    name_tw: "埃及 ",
    name_en: "Egypt",
  },
  EH: {
    country: "EH",
    iso_3166_1: "ESH",
    name_tw: "西撒哈拉 ",
    name_en: "Western Sahara",
  },
  ER: {
    country: "ER",
    iso_3166_1: "ERI",
    name_tw: "厄利垂亞",
    name_en: "Eritrea",
  },
  ES: {
    country: "ES",
    iso_3166_1: "ESP",
    name_tw: "西班牙 ",
    name_en: "Spain",
  },
  ET: {
    country: "ET",
    iso_3166_1: "ETH",
    name_tw: "衣索比亞",
    name_en: "Ethiopia",
  },
  EU: { country: "EU", iso_3166_1: "EU", name_tw: "歐盟", name_en: "EU" },
  EUR: {
    country: "EUR",
    iso_3166_1: "EUR",
    name_tw: "歐洲",
    name_en: "Europe",
  },
  FI: {
    country: "FI",
    iso_3166_1: "FIN",
    name_tw: "芬蘭 ",
    name_en: "Finland",
  },
  FJ: { country: "FJ", iso_3166_1: "FJI", name_tw: "斐濟 ", name_en: "Fiji" },
  FK: {
    country: "FK",
    iso_3166_1: "FLK",
    name_tw: "福克蘭群島 ",
    name_en: "Falkland Islands",
  },
  FM: {
    country: "FM",
    iso_3166_1: "FSM",
    name_tw: "密克羅尼西亞 ",
    name_en: "Micronesia",
  },
  FO: {
    country: "FO",
    iso_3166_1: "FRO",
    name_tw: "法羅群島 ",
    name_en: "Faroe Islands",
  },
  FR: {
    country: "FR",
    iso_3166_1: "FRA",
    name_tw: "法國 ",
    name_en: "France",
  },
  GA: { country: "GA", iso_3166_1: "GAB", name_tw: "加彭", name_en: "Gabon" },
  GB: {
    country: "GB",
    iso_3166_1: "GBR",
    name_tw: "英國 ",
    name_en: "United Kingdom",
  },
  GD: {
    country: "GD",
    iso_3166_1: "GRD",
    name_tw: "格瑞那達",
    name_en: "Grenada",
  },
  GE: {
    country: "GE",
    iso_3166_1: "GEO",
    name_tw: "喬治亞",
    name_en: "Georgia",
  },
  GH: {
    country: "GH",
    iso_3166_1: "GHA",
    name_tw: "加納 ",
    name_en: "Ghana",
  },
  GI: {
    country: "GI",
    iso_3166_1: "GIB",
    name_tw: "直布羅陀 ",
    name_en: "Gibraltar",
  },
  GL: {
    country: "GL",
    iso_3166_1: "GRL",
    name_tw: "格陵蘭 ",
    name_en: "Greenland",
  },
  GM: {
    country: "GM",
    iso_3166_1: "GMB",
    name_tw: "甘比亞",
    name_en: "Gambia",
  },
  GN: {
    country: "GN",
    iso_3166_1: "GIN",
    name_tw: "幾內亞 ",
    name_en: "Guinea",
  },
  GQ: {
    country: "GQ",
    iso_3166_1: "GNQ",
    name_tw: "赤道幾內亞 ",
    name_en: "Equatorial Guinea",
  },
  GR: {
    country: "GR",
    iso_3166_1: "GRC",
    name_tw: "希臘 ",
    name_en: "Greece",
  },
  GT: {
    country: "GT",
    iso_3166_1: "GTM",
    name_tw: "瓜地馬拉",
    name_en: "Guatemala",
  },
  GU: { country: "GU", iso_3166_1: "GUM", name_tw: "關島 ", name_en: "Guam" },
  GW: {
    country: "GW",
    iso_3166_1: "GNB",
    name_tw: "幾內亞比紹 ",
    name_en: "Guinea-Bissau",
  },
  GY: {
    country: "GY",
    iso_3166_1: "GUY",
    name_tw: "蓋亞那",
    name_en: "Guyana",
  },
  HK: {
    country: "HK",
    iso_3166_1: "HKG",
    name_tw: "香港 ",
    name_en: "Hong Kong",
  },
  HN: {
    country: "HN",
    iso_3166_1: "HND",
    name_tw: "洪都拉斯 ",
    name_en: "Honduras",
  },
  HR: {
    country: "HR",
    iso_3166_1: "HRV",
    name_tw: "克羅埃西亞",
    name_en: "Croatia",
  },
  HT: {
    country: "HT",
    iso_3166_1: "HTI",
    name_tw: "海地 ",
    name_en: "Haiti",
  },
  HU: {
    country: "HU",
    iso_3166_1: "HUN",
    name_tw: "匈牙利 ",
    name_en: "Hungary",
  },
  ID: {
    country: "ID",
    iso_3166_1: "IDN",
    name_tw: "印尼 ",
    name_en: "Indonesia",
  },
  IE: {
    country: "IE",
    iso_3166_1: "IRL",
    name_tw: "愛爾蘭 ",
    name_en: "Ireland",
  },
  IL: {
    country: "IL",
    iso_3166_1: "ISR",
    name_tw: "以色列 ",
    name_en: "Israel",
  },
  IM: {
    country: "IM",
    iso_3166_1: "IMN",
    name_tw: "曼島",
    name_en: "Isle of Man",
  },
  IN: {
    country: "IN",
    iso_3166_1: "IND",
    name_tw: "印度 ",
    name_en: "India",
  },
  IO: {
    country: "IO",
    iso_3166_1: "IOT",
    name_tw: "英屬印度洋領地 ",
    name_en: "British Indian Ocean Territory",
  },
  IQ: {
    country: "IQ",
    iso_3166_1: "IRQ",
    name_tw: "伊拉克 ",
    name_en: "Iraq",
  },
  IR: { country: "IR", iso_3166_1: "IRN", name_tw: "伊朗 ", name_en: "Iran" },
  IS: {
    country: "IS",
    iso_3166_1: "IS",
    name_tw: "冰島 ",
    name_en: "Iceland",
  },
  IT: {
    country: "IT",
    iso_3166_1: "ITA",
    name_tw: "義大利 ",
    name_en: "Italy",
  },
  JE: {
    country: "JE",
    iso_3166_1: "JEY",
    name_tw: "澤西島",
    name_en: "Jersey",
  },
  JM: {
    country: "JM",
    iso_3166_1: "JAM",
    name_tw: "牙買加 ",
    name_en: "Jamaica",
  },
  JO: {
    country: "JO",
    iso_3166_1: "JOR",
    name_tw: "約旦",
    name_en: "Jordan",
  },
  JP: {
    country: "JP",
    iso_3166_1: "JPN",
    name_tw: "日本 ",
    name_en: "Japan",
  },
  KE: {
    country: "KE",
    iso_3166_1: "KEN",
    name_tw: "肯亞 ",
    name_en: "Kenya",
  },
  KG: {
    country: "KG",
    iso_3166_1: "KGZ",
    name_tw: "吉爾吉斯斯坦",
    name_en: "Kyrgyzstan",
  },
  KH: {
    country: "KH",
    iso_3166_1: "KHM",
    name_tw: "柬埔寨 ",
    name_en: "Cambodia",
  },
  KI: {
    country: "KI",
    iso_3166_1: "KIR",
    name_tw: "吉里巴斯",
    name_en: "Kiribati",
  },
  KM: {
    country: "KM",
    iso_3166_1: "COM",
    name_tw: "葛摩",
    name_en: "Comoros",
  },
  KN: {
    country: "KN",
    iso_3166_1: "KNA",
    name_tw: "聖克里斯多福及尼維斯",
    name_en: "Saint Kitts and Nevis",
  },
  KP: {
    country: "KP",
    iso_3166_1: "PRK",
    name_tw: "北朝鮮 ",
    name_en: "North Korea",
  },
  KR: {
    country: "KR",
    iso_3166_1: "KOR",
    name_tw: "韓國 ",
    name_en: "South Korea",
  },
  KW: {
    country: "KW",
    iso_3166_1: "KWT",
    name_tw: "科威特 ",
    name_en: "Kuwait",
  },
  KY: {
    country: "KY",
    iso_3166_1: "CYM",
    name_tw: "開曼群島 ",
    name_en: "Cayman Islands",
  },
  KZ: {
    country: "KZ",
    iso_3166_1: "KAZ",
    name_tw: "哈薩克",
    name_en: "Kazakhstan",
  },
  LA: { country: "LA", iso_3166_1: "LAO", name_tw: "寮國", name_en: "Laos" },
  LB: {
    country: "LB",
    iso_3166_1: "LBN",
    name_tw: "黎巴嫩 ",
    name_en: "Lebanon",
  },
  LC: {
    country: "LC",
    iso_3166_1: "LCA",
    name_tw: "聖露西亞",
    name_en: "Saint Lucia",
  },
  LI: {
    country: "LI",
    iso_3166_1: "LIE",
    name_tw: "列支敦斯登",
    name_en: "Liechtenstein",
  },
  LK: {
    country: "LK",
    iso_3166_1: "LKA",
    name_tw: "斯里蘭卡 ",
    name_en: "Sri Lanka",
  },
  LR: {
    country: "LR",
    iso_3166_1: "LBR",
    name_tw: "賴比瑞亞",
    name_en: "Liberia",
  },
  LS: {
    country: "LS",
    iso_3166_1: "LSO",
    name_tw: "賴索托",
    name_en: "Lesotho",
  },
  LT: {
    country: "LT",
    iso_3166_1: "LTU",
    name_tw: "立陶宛 ",
    name_en: "Lithuania",
  },
  LU: {
    country: "LU",
    iso_3166_1: "LUX",
    name_tw: "盧森堡 ",
    name_en: "Luxembourg",
  },
  LV: {
    country: "LV",
    iso_3166_1: "LVA",
    name_tw: "拉脫維亞 ",
    name_en: "Latvia",
  },
  LY: {
    country: "LY",
    iso_3166_1: "LBY",
    name_tw: "利比亞 ",
    name_en: "Libya",
  },
  MA: {
    country: "MA",
    iso_3166_1: "MAR",
    name_tw: "摩洛哥 ",
    name_en: "Morocco",
  },
  MC: {
    country: "MC",
    iso_3166_1: "MCO",
    name_tw: "摩納哥 ",
    name_en: "Monaco",
  },
  MD: {
    country: "MD",
    iso_3166_1: "MDA",
    name_tw: "摩爾多瓦",
    name_en: "Moldova",
  },
  ME: {
    country: "ME",
    iso_3166_1: "MNE",
    name_tw: "蒙特內哥羅",
    name_en: "Montenegro",
  },
  MF: {
    country: "MF",
    iso_3166_1: "MAF",
    name_tw: "聖馬丁 ",
    name_en: "Saint Martin",
  },
  MG: {
    country: "MG",
    iso_3166_1: "MDG",
    name_tw: "馬達加斯加 ",
    name_en: "Madagascar",
  },
  MH: {
    country: "MH",
    iso_3166_1: "MHL",
    name_tw: "馬紹爾群島 ",
    name_en: "Marshall Islands",
  },
  MIDEAST: {
    country: "MIDEAST",
    iso_3166_1: "MID",
    name_tw: "中東 ",
    name_en: "Middle East",
  },
  MK: {
    country: "MK",
    iso_3166_1: "MKD",
    name_tw: "馬其頓 ",
    name_en: "Macedonia",
  },
  ML: { country: "ML", iso_3166_1: "MLI", name_tw: "馬利", name_en: "Mali" },
  MM: {
    country: "MM",
    iso_3166_1: "MMR",
    name_tw: "緬甸",
    name_en: "Burma (Myanmar)",
  },
  MN: {
    country: "MN",
    iso_3166_1: "MNG",
    name_tw: "蒙古國 ",
    name_en: "Mongolia",
  },
  MO: {
    country: "MO",
    iso_3166_1: "MAC",
    name_tw: "澳門 ",
    name_en: "Macau",
  },
  MP: {
    country: "MP",
    iso_3166_1: "MNP",
    name_tw: "北馬里亞納群島 ",
    name_en: "Northern Mariana Islands",
  },
  MR: {
    country: "MR",
    iso_3166_1: "MRT",
    name_tw: "茅利塔尼亞",
    name_en: "Mauritania",
  },
  MS: {
    country: "MS",
    iso_3166_1: "MSR",
    name_tw: "蒙特塞拉特 ",
    name_en: "Montserrat",
  },
  MT: {
    country: "MT",
    iso_3166_1: "MLT",
    name_tw: "馬爾他",
    name_en: "Malta",
  },
  MU: {
    country: "MU",
    iso_3166_1: "MUS",
    name_tw: "模里西斯",
    name_en: "Mauritius",
  },
  MV: {
    country: "MV",
    iso_3166_1: "MDV",
    name_tw: "馬爾地夫",
    name_en: "Maldives",
  },
  MW: {
    country: "MW",
    iso_3166_1: "MWI",
    name_tw: "馬拉威",
    name_en: "Malawi",
  },
  MX: {
    country: "MX",
    iso_3166_1: "MEX",
    name_tw: "墨西哥 ",
    name_en: "Mexico",
  },
  MY: {
    country: "MY",
    iso_3166_1: "MYS",
    name_tw: "馬來西亞 ",
    name_en: "Malaysia",
  },
  MZ: {
    country: "MZ",
    iso_3166_1: "MOZ",
    name_tw: "莫三比克",
    name_en: "Mozambique",
  },
  NA: {
    country: "NA",
    iso_3166_1: "NAM",
    name_tw: "納米比亞 ",
    name_en: "Namibia",
  },
  NAMER: {
    country: "NAMER",
    iso_3166_1: "NAM",
    name_tw: "北美 ",
    name_en: "North America",
  },
  NC: {
    country: "NC",
    iso_3166_1: "NCL",
    name_tw: "新喀裡多尼亞 ",
    name_en: "New Caledonia",
  },
  NE: { country: "NE", iso_3166_1: "NER", name_tw: "尼日", name_en: "Niger" },
  NF: {
    country: "NF",
    iso_3166_1: "NFK",
    name_tw: "諾福克島 ",
    name_en: "Norfolk Island",
  },
  NG: {
    country: "NG",
    iso_3166_1: "NGA",
    name_tw: "奈及利亞",
    name_en: "Nigeria",
  },
  NI: {
    country: "NI",
    iso_3166_1: "NIC",
    name_tw: "尼加拉瓜 ",
    name_en: "Nicaragua",
  },
  NL: {
    country: "NL",
    iso_3166_1: "NLD",
    name_tw: "荷蘭 ",
    name_en: "Netherlands",
  },
  NO: {
    country: "NO",
    iso_3166_1: "NOR",
    name_tw: "挪威 ",
    name_en: "Norway",
  },
  NP: {
    country: "NP",
    iso_3166_1: "NPL",
    name_tw: "尼泊爾 ",
    name_en: "Nepal",
  },
  NR: { country: "NR", iso_3166_1: "NRU", name_tw: "諾魯", name_en: "Nauru" },
  NU: { country: "NU", iso_3166_1: "NIU", name_tw: "紐埃 ", name_en: "Niue" },
  NZ: {
    country: "NZ",
    iso_3166_1: "NZL",
    name_tw: "紐西蘭 ",
    name_en: "New Zealand",
  },
  OM: { country: "OM", iso_3166_1: "OMN", name_tw: "阿曼 ", name_en: "Oman" },
  PA: {
    country: "PA",
    iso_3166_1: "PAN",
    name_tw: "巴拿馬 ",
    name_en: "Panama",
  },
  PE: { country: "PE", iso_3166_1: "PER", name_tw: "秘魯 ", name_en: "Peru" },
  PF: {
    country: "PF",
    iso_3166_1: "PYF",
    name_tw: "法屬波利尼西亞 ",
    name_en: "French Polynesia",
  },
  PG: {
    country: "PG",
    iso_3166_1: "PNG",
    name_tw: "巴布亞紐幾內亞",
    name_en: "Papua New Guinea",
  },
  PH: {
    country: "PH",
    iso_3166_1: "PHL",
    name_tw: "菲律賓 ",
    name_en: "Philippines",
  },
  PK: {
    country: "PK",
    iso_3166_1: "PAK",
    name_tw: "巴基斯坦 ",
    name_en: "Pakistan",
  },
  PL: {
    country: "PL",
    iso_3166_1: "POL",
    name_tw: "波蘭 ",
    name_en: "Poland",
  },
  PM: {
    country: "PM",
    iso_3166_1: "SPM",
    name_tw: "聖皮耶與密克隆群島",
    name_en: "Saint Pierre and Miquelon",
  },
  PN: {
    country: "PN",
    iso_3166_1: "PCN",
    name_tw: "皮特肯群島",
    name_en: "Pitcairn Islands",
  },
  PR: {
    country: "PR",
    iso_3166_1: "PRI",
    name_tw: "波多黎各 ",
    name_en: "Puerto Rico",
  },
  PT: {
    country: "PT",
    iso_3166_1: "PRT",
    name_tw: "葡萄牙 ",
    name_en: "Portugal",
  },
  PW: { country: "PW", iso_3166_1: "PLW", name_tw: "帛琉", name_en: "Palau" },
  PY: {
    country: "PY",
    iso_3166_1: "PRY",
    name_tw: "巴拉圭 ",
    name_en: "Paraguay",
  },
  QA: { country: "QA", iso_3166_1: "QAT", name_tw: "卡達", name_en: "Qatar" },
  RO: {
    country: "RO",
    iso_3166_1: "ROU",
    name_tw: "羅馬尼亞 ",
    name_en: "Romania",
  },
  RS: {
    country: "RS",
    iso_3166_1: "SRB",
    name_tw: "塞爾維亞 ",
    name_en: "Serbia",
  },
  RU: {
    country: "RU",
    iso_3166_1: "RUS",
    name_tw: "俄羅斯 ",
    name_en: "Russia",
  },
  RW: {
    country: "RW",
    iso_3166_1: "RWA",
    name_tw: "盧安達",
    name_en: "Rwanda",
  },
  SA: {
    country: "SA",
    iso_3166_1: "SAU",
    name_tw: "沙烏地阿拉伯",
    name_en: "Saudi Arabia",
  },
  SAMER: {
    country: "SAMER",
    iso_3166_1: "SAM",
    name_tw: "南美 ",
    name_en: "South America",
  },
  SB: {
    country: "SB",
    iso_3166_1: "SLB",
    name_tw: "索羅門群島 ",
    name_en: "Solomon Islands",
  },
  SC: {
    country: "SC",
    iso_3166_1: "SYC",
    name_tw: "塞席爾",
    name_en: "Seychelles",
  },
  SD: {
    country: "SD",
    iso_3166_1: "SDN",
    name_tw: "蘇丹 ",
    name_en: "Sudan",
  },
  SE: {
    country: "SE",
    iso_3166_1: "SWE",
    name_tw: "瑞典 ",
    name_en: "Sweden",
  },
  SG: {
    country: "SG",
    iso_3166_1: "SGP",
    name_tw: "新加坡 ",
    name_en: "Singapore",
  },
  SH: {
    country: "SH",
    iso_3166_1: "SHN",
    name_tw: "聖赫勒拿 ",
    name_en: "Saint Helena",
  },
  SI: {
    country: "SI",
    iso_3166_1: "SVN",
    name_tw: "斯洛維尼亞",
    name_en: "Slovenia",
  },
  SJ: {
    country: "SJ",
    iso_3166_1: "SJM",
    name_tw: "斯瓦爾巴 ",
    name_en: "Svalbard",
  },
  SK: {
    country: "SK",
    iso_3166_1: "SVK",
    name_tw: "斯洛伐克 ",
    name_en: "Slovakia",
  },
  SL: {
    country: "SL",
    iso_3166_1: "SLE",
    name_tw: "獅子山",
    name_en: "Sierra Leone",
  },
  SM: {
    country: "SM",
    iso_3166_1: "SMR",
    name_tw: "聖馬利諾",
    name_en: "San Marino",
  },
  SN: {
    country: "SN",
    iso_3166_1: "SEN",
    name_tw: "塞內加爾 ",
    name_en: "Senegal",
  },
  SO: {
    country: "SO",
    iso_3166_1: "SOM",
    name_tw: "索馬利亞",
    name_en: "Somalia",
  },
  SR: {
    country: "SR",
    iso_3166_1: "SUR",
    name_tw: "蘇利南",
    name_en: "Suriname",
  },
  ST: {
    country: "ST",
    iso_3166_1: "STP",
    name_tw: "聖多美和普林西比 ",
    name_en: "Sao Tome and Principe",
  },
  SV: {
    country: "SV",
    iso_3166_1: "SLV",
    name_tw: "薩爾瓦多 ",
    name_en: "El Salvador",
  },
  SY: {
    country: "SY",
    iso_3166_1: "SYR",
    name_tw: "敘利亞 ",
    name_en: "Syria",
  },
  SZ: {
    country: "SZ",
    iso_3166_1: "SWZ",
    name_tw: "史瓦濟蘭 ",
    name_en: "Swaziland",
  },
  TC: {
    country: "TC",
    iso_3166_1: "TCA",
    name_tw: "特克斯和凱科斯群島 ",
    name_en: "Turks and Caicos Islands",
  },
  TD: { country: "TD", iso_3166_1: "TCD", name_tw: "查德", name_en: "Chad" },
  TG: { country: "TG", iso_3166_1: "TGO", name_tw: "多哥 ", name_en: "Togo" },
  TH: {
    country: "TH",
    iso_3166_1: "THA",
    name_tw: "泰國 ",
    name_en: "Thailand",
  },
  TJ: {
    country: "TJ",
    iso_3166_1: "TJK",
    name_tw: "塔吉克",
    name_en: "Tajikistan",
  },
  TK: {
    country: "TK",
    iso_3166_1: "TKL",
    name_tw: "托克勞 ",
    name_en: "Tokelau",
  },
  TL: {
    country: "TL",
    iso_3166_1: "TLS",
    name_tw: "東帝汶 ",
    name_en: "Timor-Leste",
  },
  TM: {
    country: "TM",
    iso_3166_1: "TKM",
    name_tw: "土庫曼",
    name_en: "Turkmenistan",
  },
  TN: {
    country: "TN",
    iso_3166_1: "TUN",
    name_tw: "突尼斯 ",
    name_en: "Tunisia",
  },
  TO: { country: "TO", iso_3166_1: "TON", name_tw: "東加", name_en: "Tonga" },
  TR: {
    country: "TR",
    iso_3166_1: "TUR",
    name_tw: "土耳其",
    name_en: "Turkey",
  },
  TT: {
    country: "TT",
    iso_3166_1: "TTO",
    name_tw: "千里達及托巴哥",
    name_en: "Trinidad and Tobago",
  },
  TV: {
    country: "TV",
    iso_3166_1: "TUV",
    name_tw: "吐瓦魯",
    name_en: "Tuvalu",
  },
  TW: {
    country: "TW",
    iso_3166_1: "TWN",
    name_tw: "台灣 ",
    name_en: "Taiwan",
  },
  TZ: {
    country: "TZ",
    iso_3166_1: "TZA",
    name_tw: "坦尚尼亞",
    name_en: "Tanzania",
  },
  UA: {
    country: "UA",
    iso_3166_1: "UKR",
    name_tw: "烏克蘭 ",
    name_en: "Ukraine",
  },
  UG: {
    country: "UG",
    iso_3166_1: "UGA",
    name_tw: "烏干達 ",
    name_en: "Uganda",
  },
  US: {
    country: "US",
    iso_3166_1: "USA",
    name_tw: "美國 ",
    name_en: "United States",
  },
  UY: {
    country: "UY",
    iso_3166_1: "URY",
    name_tw: "烏拉圭 ",
    name_en: "Uruguay",
  },
  UZ: {
    country: "UZ",
    iso_3166_1: "UZB",
    name_tw: "烏茲別克斯坦 ",
    name_en: "Uzbekistan",
  },
  VA: {
    country: "VA",
    iso_3166_1: "VAT",
    name_tw: "羅馬教廷（梵蒂岡） ",
    name_en: "Holy See (Vatican City)",
  },
  VC: {
    country: "VC",
    iso_3166_1: "VCT",
    name_tw: "聖文森及格瑞那丁",
    name_en: "Saint Vincent and the Grenadines",
  },
  VE: {
    country: "VE",
    iso_3166_1: "VEN",
    name_tw: "委內瑞拉 ",
    name_en: "Venezuela",
  },
  VG: {
    country: "VG",
    iso_3166_1: "VGB",
    name_tw: "英屬維京群島 ",
    name_en: "British Virgin Islands",
  },
  VI: {
    country: "VI",
    iso_3166_1: "VIR",
    name_tw: "美屬維京群島 ",
    name_en: "US Virgin Islands",
  },
  VN: {
    country: "VN",
    iso_3166_1: "VNM",
    name_tw: "越南 ",
    name_en: "Vietnam",
  },
  VU: {
    country: "VU",
    iso_3166_1: "VUT",
    name_tw: "萬那杜",
    name_en: "Vanuatu",
  },
  WF: {
    country: "WF",
    iso_3166_1: "WLF",
    name_tw: "瓦利斯和富圖納群島 ",
    name_en: "Wallis and Futuna",
  },
  WS: {
    country: "WS",
    iso_3166_1: "WSM",
    name_tw: "薩摩亞 ",
    name_en: "Samoa",
  },
  YE: { country: "YE", iso_3166_1: "YEM", name_tw: "葉門", name_en: "Yemen" },
  YT: {
    country: "YT",
    iso_3166_1: "MYT",
    name_tw: "馬約特島 ",
    name_en: "Mayotte",
  },
  ZA: {
    country: "ZA",
    iso_3166_1: "ZAF",
    name_tw: "南非 ",
    name_en: "South Africa",
  },
  ZM: {
    country: "ZM",
    iso_3166_1: "ZMB",
    name_tw: "尚比亞",
    name_en: "Zambia",
  },
  ZW: {
    country: "ZW",
    iso_3166_1: "ZWE",
    name_tw: "辛巴威",
    name_en: "Zimbabwe",
  },
};

export default countryTrans;
